/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUsersRouteImport } from './routes/_auth/users'
import { Route as AuthReimbursementsRouteImport } from './routes/_auth/reimbursements'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCategoriesRouteImport } from './routes/_auth/categories'
import { Route as AuthReimbursementsCreateRouteImport } from './routes/_auth/reimbursements/create'
import { Route as AuthReimbursementsEditIdRouteImport } from './routes/_auth/reimbursements/edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReimbursementsRoute = AuthReimbursementsRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesRoute = AuthCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReimbursementsCreateRoute =
  AuthReimbursementsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthReimbursementsRoute,
  } as any)
const AuthReimbursementsEditIdRoute =
  AuthReimbursementsEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthReimbursementsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AuthCategoriesRoute
  '/dashboard': typeof AuthDashboardRoute
  '/reimbursements': typeof AuthReimbursementsRouteWithChildren
  '/users': typeof AuthUsersRoute
  '/reimbursements/create': typeof AuthReimbursementsCreateRoute
  '/reimbursements/edit/$id': typeof AuthReimbursementsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AuthCategoriesRoute
  '/dashboard': typeof AuthDashboardRoute
  '/reimbursements': typeof AuthReimbursementsRouteWithChildren
  '/users': typeof AuthUsersRoute
  '/reimbursements/create': typeof AuthReimbursementsCreateRoute
  '/reimbursements/edit/$id': typeof AuthReimbursementsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/categories': typeof AuthCategoriesRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/reimbursements': typeof AuthReimbursementsRouteWithChildren
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/reimbursements/create': typeof AuthReimbursementsCreateRoute
  '/_auth/reimbursements/edit/$id': typeof AuthReimbursementsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/reimbursements'
    | '/users'
    | '/reimbursements/create'
    | '/reimbursements/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/reimbursements'
    | '/users'
    | '/reimbursements/create'
    | '/reimbursements/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/categories'
    | '/_auth/dashboard'
    | '/_auth/reimbursements'
    | '/_auth/users'
    | '/_auth/reimbursements/create'
    | '/_auth/reimbursements/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reimbursements': {
      id: '/_auth/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof AuthReimbursementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories': {
      id: '/_auth/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthCategoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reimbursements/create': {
      id: '/_auth/reimbursements/create'
      path: '/create'
      fullPath: '/reimbursements/create'
      preLoaderRoute: typeof AuthReimbursementsCreateRouteImport
      parentRoute: typeof AuthReimbursementsRoute
    }
    '/_auth/reimbursements/edit/$id': {
      id: '/_auth/reimbursements/edit/$id'
      path: '/edit/$id'
      fullPath: '/reimbursements/edit/$id'
      preLoaderRoute: typeof AuthReimbursementsEditIdRouteImport
      parentRoute: typeof AuthReimbursementsRoute
    }
  }
}

interface AuthReimbursementsRouteChildren {
  AuthReimbursementsCreateRoute: typeof AuthReimbursementsCreateRoute
  AuthReimbursementsEditIdRoute: typeof AuthReimbursementsEditIdRoute
}

const AuthReimbursementsRouteChildren: AuthReimbursementsRouteChildren = {
  AuthReimbursementsCreateRoute: AuthReimbursementsCreateRoute,
  AuthReimbursementsEditIdRoute: AuthReimbursementsEditIdRoute,
}

const AuthReimbursementsRouteWithChildren =
  AuthReimbursementsRoute._addFileChildren(AuthReimbursementsRouteChildren)

interface AuthRouteChildren {
  AuthCategoriesRoute: typeof AuthCategoriesRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthReimbursementsRoute: typeof AuthReimbursementsRouteWithChildren
  AuthUsersRoute: typeof AuthUsersRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCategoriesRoute: AuthCategoriesRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthReimbursementsRoute: AuthReimbursementsRouteWithChildren,
  AuthUsersRoute: AuthUsersRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
